### ISSUE TITLE
[Design] 유저 정보 페이지 퍼블리싱

### ISSUE THREAD

**Issue by rachel4w2** [SV-Summer-BootCamp-Team-F/frontend#10]
**구현 할 기능에 대한 설명**
유저 정보 페이지 와이어프레임 구성 및 퍼블리싱

**TODO List**
- [ ]  와이어 프레임 구성하기
- [ ]  피그마 디자인하기
- [ ]  유저 정보 컴포넌트 만들기
- [ ]  highcharts로 차트 컴포넌트 만들기
- [ ]  멘토님께 피드백받기

**참고 자료**
디자인 컨셉과 관련된 추가 정보나 스크린샷 등이 있다면 첨부해 주세요.
