### ISSUE TITLE
[Feature] 관계 페이지 추가기능 구현, 디자인 개선

### ISSUE THREAD

**Issue by TMInstaller** [SV-Summer-BootCamp-Team-F/frontend#14]
**기능에 대한 설명**

1. 업데이트 했을 때 위치 다시 중앙으로 돌리기
업데이트 버튼을 통해 중앙으로 돌리고 줌 상태도 초기화하는 데 성공했지만 마우스로 드래그를 하려고 할 시 바로 이전의 위치와 줌 상태로 돌아간다는 점을 해결해야 한다.

2. types 파일의 이름 변경 필요성
타입의 종류를 한 번 더 나누어 유지보수에 도움이 될 형태로 이름을 변경하면 좋을 것으로 보인다

3. 관계도에 맞는 그래프 새로 설정 필요
임시로 점 형태의 그래프를 나타내었지만, 실제로 구현해야 하는 부분은 노드와 노드간의 관계를 나타내는 그래프이므로 이 부분에 대한 작업이 필요하다

4. SVG에 배경 넣기
현재는 SVG를 화면 크기에 맞게 넓혀둔 상태이고, 그 위에 UI들을 넣어둔 페이지의 구성을 하고 있다
SVG에 배경을 넣는 방법을 찾아서 실제 디자인 컨셉에 가깝게 구현할 예정이다

**TODO List**
- [ ] 업데이트 했을 때 위치 다시 중앙으로 돌리기 
- [ ] types 파일의 이름 변경 필요성
- [ ] 관계도에 맞는 그래프 새로 설정 필요
- [ ] SVG에 배경 넣기

**참고 자료**
https://time-map-installer.tistory.com/247
