### ISSUE TITLE
[Design] 유저 정보 페이지 디자인 수정

### ISSUE THREAD

**Issue by rachel4w2** [SV-Summer-BootCamp-Team-F/frontend#21]
**구현 할 기능에 대한 설명**
- 유저 페이지의 디자인을 수정합니다.

**TODO List**
- [ ]  chart 부분 그리드 & 컴포넌트 수정
- [ ]  card info 부분 명함 사진 추가
- [ ]  배경 디자인 결정

**참고 자료**
디자인 컨셉과 관련된 추가 정보나 스크린샷 등이 있다면 첨부해 주세요.
