### ISSUE TITLE
[Chore] TailwindCSS 초기 세팅

### ISSUE THREAD

**Issue by TMInstaller** [SV-Summer-BootCamp-Team-F/frontend#3]
**세팅에 대한 설명**
tailwind.config.cjs 세팅 예정

**TODO List**
- [ ] 3가지의 시그니처 컬러 추가하기
- [ ] 1 rem을 10px로 수정하기(이전 16px)
- [ ] 그 외 필요한 기능들 커스텀해두기

**참고 자료**
세팅과 관련된 추가 정보나 스크린샷 등이 있다면 첨부해 주세요.
