### ISSUE TITLE
[Design] highchart 및 유저 페이지 디자인 수정

### ISSUE THREAD

**Issue by rachel4w2** [SV-Summer-BootCamp-Team-F/frontend#40]
**구현 할 기능에 대한 설명**
highchart 디자인을 수정할 예정입니다.

**TODO List**
- [ ]  소개 페이지 차트 사용하지 않는 버튼과 워터마크 제거
- [ ]  유저 페이지 차트 mock 데이터 수정
- [ ]  유저 페이지 차트 라벨링 수정
- [ ]  유저 페이지 영어 -> 한글로 수정

**참고 자료**
디자인 컨셉과 관련된 추가 정보나 스크린샷 등이 있다면 첨부해 주세요.
